sudo: required
matrix:
  fast_finish: true
services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod 755 ~/.docker
- chmod 644 ~/.docker/config.json
- ./build.sh

env:
  global:
    - DOCKER_USERNAME: angrygoat
    - secure: "F3EvzS+vofHsiBbba3GAbBBFi9M5R8Dz1u47lCEm7CL67V0rIuttBmfDR+byMwsEwZkce2yd2D06lQfcE6WY8fOMa+UPbjCL77WCKsE/Cv9eUkhb+lkRymZrAwevJAM1USYRfdNKH5jMLDFX8itP3pzopC8cL1zv2EoiYj5p6teKIa8J5IiBMYtKfxijQv3rJm6VKZ/LTt7fJG4435NAoByOcIdL7vsuRghaB4aKl3MLzOtvgL70Ogu/MAIncFgZgQ0ST6ca1GcyxQ89tSWZdwppDZ3vpli3GGNRkQRfRqoRiZAnL1d7ezDSiX/o1+wtAuiOam1VN2cMQfHysYrs9e8+cDpADs7v3TrMVoed1OofjhGzVpob+a86YxF/ptZYUJ7Lgxp6etbQHqiSFiYQz3AvHxmayJU94u5jav9BGs311165c7nNAQ44YSBWYBl8r2aHmDA4yehU2nVB/BdfMhOqpZJ5HJXaZU+qPfu36fPZowdl/uXqRysqwzCNbIgBDZaGQejKOXxH4xYaTFeMDJURHLUT0y9SWC2LDKhc0AzwsYHR7lW0pm312etW2UVBWwo2s1uYw+NZ1jPkhxFyjg0kowpfOlZTaxQo/bFr/3+GEbzA7nqU+fOtQHqbyQVC3s4RHOBnCSIQFREL3GXHPCdUTY5+t5pEqtGhflKf0No="
